name: Update Archives

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: [ master ]
    paths: 
      - 'Script/**'
      - '.github/workflows/**'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
        
    - name: Install dependencies
      run: |
        cd Script
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update Archives
      run: |
        cd Script
        python update.py
        
    - name: Commit files
      run: |
        git config --local user.email "BlogArchives@github.com"
        git config --local user.name "BlogArchivesBot"
        git add .
        git commit -m "Update Archives." || true
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
